### ISSUE TITLE
More interface options for Dolt.import_df

### ISSUE THREAD

**Issue by timsehn** [liquidata-inc/doltpy#15] opened 2020-04-29 22:03 UTC
I think we need to blow out the import interface, as cool as Pandas DataFrames are.

I think we should accept at least three formats:

1. Dataframes
2. `[{col: val, ...}]`
3. `[[val, val, ...]]` - with and without header row.

I also think the import type should be a instance of the import not a parameter you pass if we can:

1. `dolt.import.create()`
2. `dolt.import.replace()`
3. `dolt.import.update()`

Those can be underscores not `.` if having an import class is not "python-y". I'm a python noob.

**Comment by timsehn** [comment] 2020-04-29 22:04
I think we should also support these formats as read outputs for tables and sql queries as well.

**Comment by oscarbatori** [comment] 2020-05-06 06:07
Duplicate of #20

**Comment by oscarbatori** [comment] 2020-05-06 06:09
I think this is a good idea for DataFrames, they have a schema and translating that to a SQL schema should be straight forward. I believe Pandas may already implement this.

For lists and dictionaries it's a little complicated, but I basically see four logical things to support:
1. List of lists (column major): each element of the outer list represents a column, and holds a list of values, to type inference we have to scan each column-list of values and choose a super type
2. List of lists (row major): each element of the outer list represents a row, and holds a list of values, one for each column. Again we have to scan each column and choose the super type of the elements, and map it to SQL.
3. List of dicts (row major): each element of the outer list represents a row, and each row is a dict mapping column name to value. To do type inference we scan the rows, and find the super type for each column.
4. Dict of lists (column major): dict maps column names to lists of values, we scan each list and infer the super type.

A quick and dirty version of this would be to simply try and convert the users' data to Pandas, and then use the resulting DataFrame to infer schema.

**Comment by oscarbatori** [comment] 2020-05-21 19:27
@timsehn - here is my proposal for enhancing this interface. I don't think column-major lists of lists is necessary. Also, I think a function per import type would create a lot of functions, and I don't think that we want to do that.  Let me know what you think.
 
```python
def import_dict(self,
                table_name: str,
                data: dict,
                primary_keys: List[str] = None,
                import_mode: str = None):
    """
    COLUMN MAJOR (note this sort of takes care of list of list column major since user would have to provide such a function with column information anyway)

    Import a dict mapping keys to lists of values for the rows. All lists must be of identical length. Suppose we have a table as follows:
        CREATE TABLE players (id INT, name VARCHAR(16), PRIMARY KEY (id))

    >>> dict_of_lists = {'id': [1, 2], 'name': ['Roger', 'Rafael']}
    >>> repo.import_dict('players', dict_of_lists, import_mode='update')

    Note that we can run this in create mode using the

    Assertions:
        - all list values are of equal length
        - each list value has elements that can be cast to a common supertype that can be cast to the type of the column whose name the key to the list value

    """
    pass

def import_list_of_lists(self,
                         table_name: str,
                         data: List[List[Any]],
                         col_list: List[str] = None,
                         primary_keys: List[str] = None,
                         import_mode: str = None):
    """
    ROW MAJOR

    Suppose we have a table with columns id and name of types int and string respectively. Let's suppose we have a table created as follows:
        CREATE TABLE players (id INT, name VARCHAR(16), PRIMARY KEY (id))

    First case, a list of lists. This can be used only for updates since it provides no reasonable way to infer column names. The code looks something like:
    >>> list_of_lists = [[1, 'Roger'], [2, 'Rafael']]
    >>> repo.import_list('players', list_of_lists, import_mode='update')

    Note, there was no need to include a primary key since we can only update in this mode.

    Assertions:
        - all elements of outter list have same length, same length as number of columns in the table
        - all elements of each list have a common super type that can be cast (without informaiton loss to the type of the column)
    """
    pass

def import_list_of_dicts(self,
                         table_name: str,
                         data: dict,
                         primary_keys: List[str] = None,
                         import_mode: str = None):
    """
    ROW MAJOR
    
    Suppose we have alist element of the list is a dict mapping column names to values. Again we have a table created by:
        CREATE TABLE players (id INT, name VARCHAR(16), PRIMARY KEY (id))

    Now
    >>> list_of_dicts = [{'id': 1, 'name': 'Roger'}, {'id': 2, 'name': 'Rafael'}]
    >>> repo.import_list('players', list_of_dicts, import_mode='update')

    Note that since we get the column names, and we can infer the types from the values (cast to common parent), then we can also use this for create mode, passing priamry key:
    >>> repo.import_list('players', list_of_dicts, ['id'], import_mode='create')

    Assertions
        - all elements of the outter list are dictionaries with the same keys
        - all values across all dictionaries that are the elements of th outter list cast to a common super type that can be cast to the type of the column the particular key is the the name of
    """
    pass
```

**Comment by timsehn** [comment] 2020-05-21 19:33
This is a vast improvement over what we have.

**Comment by oscarbatori** [comment] 2020-06-08 23:04
1.0.0 contains these interfaces.

**Closed by oscarbatori** 2020-06-08 23:04 UTC
Labels: enhancement
