### ISSUE TITLE
Dolt.schema_import should support a dataframe, {}, and [] interface

### ISSUE THREAD

**Issue by timsehn** [liquidata-inc/doltpy#20] opened 2020-05-05 20:26 UTC
We should support DataFrames, lists and dictionaries as supported input to schema_import. We should also allow the user to control replace, create, etc.

**Comment by oscarbatori** [comment] 2020-05-06 06:05
I think this is a good idea for DataFrames, they have a schema and translating that to a SQL schema should be straight forward. I believe Pandas may already implement this.

For lists and dictionaries it's a little complicated, but I basically see four logical things to support:
1. List of lists (column major): each element of the outer list represents a column, and holds a list of values, to type inference we have to scan each column-list of values and choose a super type
2. List of lists (row major): each element of the outer list represents a row, and holds a list of values, one for each column. Again we have to scan each column and choose the super type of the elements, and map it to SQL.
3. List of dicts (row major): each element of the outer list represents a row, and each row is a dict mapping column name to value. To do type inference we scan the rows, and find the super type for each column.
4. Dict of lists (column major): dict maps column names to lists of values, we scan each list and infer the super type.

A quick and dirty version of this would be to simply try and convert the users' data to Pandas, and then use the resulting DataFrame to infer schema.

**Comment by oscarbatori** [comment] 2020-05-06 06:08
Duplicate of #15

**Closed by oscarbatori** 2020-05-06 06:08 UTC
